// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJ1355MiqQG2oL7jLhRLC4kk8CdQeRmM',
    appId: '1:549680451365:web:2aa2dcd0d2b9dfb00814cc',
    messagingSenderId: '549680451365',
    projectId: 'footprints-app-c3790',
    authDomain: 'footprints-app-c3790.firebaseapp.com',
    storageBucket: 'footprints-app-c3790.appspot.com',
    measurementId: 'G-WTHNHQL94S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgIaXmYoMNmyo3qZhwF6D8uT1DS0suNM',
    appId: '1:549680451365:android:53c41131d9eda9810814cc',
    messagingSenderId: '549680451365',
    projectId: 'footprints-app-c3790',
    storageBucket: 'footprints-app-c3790.appspot.com',
  );
}
